version: '3'
services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bill_provider
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always